# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/pyxis/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/pyxis

PRODUCT_COPY_FILES += \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensor.pyxis_imx582.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensor.pyxis_imx582.so \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensor.pyxis_imx586.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensor.pyxis_imx586.so \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensormodule.pyxis_luxvisions_imx582_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.pyxis_luxvisions_imx582_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensormodule.pyxis_luxvisions_imx586_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.pyxis_luxvisions_imx586_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.sensormodule.pyxis_ofilm_imx582_cn_ii.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.pyxis_ofilm_imx582_cn_ii.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_luxvisions_imx582_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_luxvisions_imx582_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_luxvisions_imx586_cn_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_luxvisions_imx586_cn_i.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_ofilm_imx582_cn_ii.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_ofilm_imx582_cn_ii.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_ofilm_s5kgd1_cn_ii_global.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_ofilm_s5kgd1_cn_ii_global.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/camera/com.qti.tuned.pyxis_sunny_s5kgd1_cn_i_global.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.pyxis_sunny_s5kgd1_cn_i_global.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/libmibokeh_712.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmibokeh_712.so \
    vendor/xiaomi/pyxis/proprietary/vendor/lib/mibokeh_712_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/lib/mibokeh_712_opencl.bin \
    vendor/xiaomi/pyxis/proprietary/vendor/lib64/libmibokeh_712.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmibokeh_712.so \
    vendor/xiaomi/pyxis/proprietary/vendor/etc/dsi_ss_ea8076_fhd_cmd_display_f3b_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dsi_ss_ea8076_fhd_cmd_display_f3b_mi.xml
